name: e_commerce_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
    # Icons
  iconsax: ^0.0.8
  # Utility Packages
  http: ^1.2.0
  logger: ^2.0.2+1
  intl: ^0.19.0
  url_launcher: ^6.2.4
  # State Management
  get: 4.6.6
  get_storage: ^2.1.1
  flutter_native_splash: ^2.3.11
  lottie: ^3.1.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animation/
    - assets/images/banners/
    - assets/logos/
    - assets/icons/
    - assets/icons/brands/
    - assets/icons/categories/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800